### ISSUE TITLE
Main block is not centered

### ISSUE THREAD

**Issue by noobite** [iKreativ/Workless#4]
The main (white) block is not centered inside the container. In fact when resizing down the browser you can clearly see that the left border is 2 times much smaller than the right one.

I've noticed in `workless.css` that the `#main` width misses 50px. So for exemple changing :

``` css
@media only screen and (min-width: 1025px) {

    p { font-size: 14px; }

    .container {
        width: 1024px;
        margin: 0 auto;
    }

    #main {
        width: 924px;
    }
```

to :

``` css

@media only screen and (min-width: 1025px) {

    p { font-size: 14px; }

    .container {
        width: 1024px;
        margin: 0 auto;
    }

    #main {
        width: 974px;
    }
```

solves this issue. Not sure about the calculations but changes certainly also have to be made to others classes inside the media query like `.container`, `.one_full` etc.
